<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PromptProcessor.Worker-2cea10b9-6b08-4643-ad93-f30606b2a64f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PromptProcessor.Domain\PromptProcessor.Domain.csproj" />
    <ProjectReference Include="..\PromptProcessor.Infrastructure\PromptProcessor.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PromptProcessor.Tests" />
  </ItemGroup>
</Project>
